#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
@Project: poozos_albatross
@Date: 5/27/26
@File: waft_gogo

@Author: Silenuz Nowan (silenuznowan@yahoo.com)

This module parses Doxygen generated XML documentation and attempts to generate
GDExtension build_profile.json file.

Gogo: "You're sure it was this evening?"
Didi: "What?"
Gogo: "That we were to wait."
Didi: "He said Saturday. (Pause) I think."
"""
import sys
import json
import re
from collections import namedtuple
from pathlib import Path
from xml.etree import ElementTree as et
import luckys_zephyr as lz

xml_input_folder = sys.argv[1]
dest_folder = sys.argv[2]
src_folder = Path(dest_folder)

build_profile = dict()
build_profile['_'] = 'Build Profile Generated from Doxygen XML'
build_profile['type'] = 'feature_profile'
build_profile['enabled_classes'] = []
build_profile['enabled_classes'].append("OS")

def create_include_dictionary(lucky_data):
    includes = lucky_data.get_include_values()
    for include in includes:
        if include not in build_profile['enabled_classes']:
            build_profile['enabled_classes'].append(include)


def write_output():
    file_name = src_folder / 'build_profile_gen.json'
    with open(file_name, 'w') as f:
        json.dump(build_profile, f,indent=4)


def parse_class_xml_files() -> None:
    """
    loop through the class documentation files generated by doxygen and
    create a Godot class document file for each
    :return: None
    """
    files = list(Path(xml_input_folder).rglob('class*.xml'))
    for file in files:
        lucky_data = lz.LuckyZephyr(file)
        create_include_dictionary(lucky_data)
        write_output()

if __name__ == '__main__':
    parse_class_xml_files()